name: leap
description: An opinionated toolkit for creating 2D platformers on top of Flame engine.
version: 0.0.1
homepage: https://github.com/kurtome/leap

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.3.0
  flame_behaviors: ^0.1.1
  flame_tiled: ^1.7.2
  flutter:
    sdk: flutter
  tiled: ^0.8.4

dev_dependencies:
  flame_lint: ^0.1.2
  flutter_test:
    sdk: flutter
